### ISSUE TITLE
Creating a new Engine during script execution doesn't work

### ISSUE THREAD

**Issue by ratkingsminion** [wixette/isb#21]
I don't have a simple test case for this right now, but the situation is that I have rooms in my game, and each room has its own ISB Engine for execution of scripts. So when a method - called during the execution of an ISB script - creates a new Room and a new Engine(), I get strange behaviour and esoteric bugs. (For example, a StringValue I had as parameter became a number.) I solved the problem by moving the creation of the new Engine() to the next frame.

The question is if this is expected behaviour, or if this is some kind of edge case?

**Comment by wixette** [comment]
> ... when a method - called during the execution of an ISB script - creates a new Room and a new Engine() ...

Did your program behave like the following steps?

1. Creates and runs Engine A.
2. Engine A compiles and runs Script X.
3. Within Script X, a BASIC statement calls a custom lib function, say, LibFoo.Bar().
4. The C# implementation of LibFoo.Bar() creates and runs a new engine, say, Engine B.
5. Strange behaviors are observed when Engine B is running some other BASIC script, say Script Y.

Is this the situation that you had observed?

**Comment by ratkingsminion** [comment]
Yes, exactly.

**Comment by wixette** [comment]
ISB supports multiple engines by design. But I've never carefully considered the nested case such as engineA->scriptX->engineB->scriptY.

I created two experimental branches to demo the nested-engine case. So far everything works correctly. No strange issue is detected. Feel free to modify them and try something that is more relevant to your case.

Exp 1: Start an inner ISB Engine from Foo.Bar() - The outer engine calls the blocking version of Run...

https://github.com/wixette/isb/blob/exp_wixette_innerengine_blocking/unity_integration_demo/Assets/Scripts/Program.cs

Exp 2: The outer engine calls the non-blocking version of Run... as in a Unity coroutine.

https://github.com/wixette/isb/blob/exp_wixette_innerengine/unity_integration_demo/Assets/Scripts/Program.cs

**Comment by ratkingsminion** [comment]
I can't recreate my test case unfortunately, so if you want you can close this issue, and if it should ever come back for me, I would just reopen it.
